services:
  # Neo4j as the graph database
  neo4j:
    image: neo4j:5.26.17-community
    restart: unless-stopped
    container_name: neo4j
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      # The full APOC plugin is required for advanced query and dynamic insertion capabilities
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins

  # MongoDB as the primary document database
  mongodb:
    image: mongo:8.2.2
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Redis as the caching layer
  redis:
    image: redis:8.4
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data

  # Qdrant as the vector database
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage

  # Primary service
  bioterms:
    # Defaults to the GPU version; if you prefer lightweight CPU-only, change the image to:
    # image: firefox2100/biomedical-terminology-service:latest-cpu
    image: firefox2100/biomedical-terminology-service:latest
    restart: unless-stopped
    container_name: bioterms
    # This section enables GPU support; remove if not needed
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - neo4j
      - mongodb
      - redis
      - qdrant
    ports:
      - "5000:5000"
    environment:
      # Any of the following environment variables can be adjusted as needed
      # Or can be loaded from docker secrets for better security in production
      - BTS_PROCESS_LIMIT=4
      - BTS_LOGGING_LEVEL=INFO
      - BTS_SECRET_KEY=secret-key
      - BTS_SERVER_HMAC_KEY=your-hmac-key
      - BTS_USE_HTTPS=false
      - BTS_ENABLE_METRICS=true
      - BTS_SERVICE_ROOT_PATH=
      - BTS_OPENAPI_URL=/openapi.json
      - BTS_DOCS_URL=/docs
      - BTS_REDOC_URL=/redoc
      - BTS_ENVIRONMENT=dev
      - BTS_DOC_DATABASE_DRIVER=mongo
      - BTS_MONGODB_HOST=mongodb
      - BTS_MONGODB_PORT=27017
      - BTS_MONGODB_DB_NAME=bts
      - BTS_MONGODB_USERNAME= # Leave blank if not using authentication
      - BTS_MONGODB_PASSWORD= # Leave blank if not using authentication
      - BTS_GRAPH_DATABASE_DRIVER=neo4j
      - BTS_NEO4J_URI=neo4j://neo4j:7687
      - BTS_NEO4J_DB_NAME=neo4j
      - BTS_NEO4J_USERNAME=neo4j
      - BTS_NEO4J_PASSWORD=password
      - BTS_CACHE_DRIVER=redis
      - BTS_REDIS_HOST=redis
      - BTS_REDIS_PORT=6379
      - BTS_REDIS_DB=0
      - BTS_BIOPORTAL_API_KEY=your-bioportal-api-key
      - BTS_NHS_TRUD_API_KEY=your-nhs-trud-api-key
      - BTS_TRANSFORMER_MODEL_NAME=BAAI/bge-base-en-v1.5
      - BTS_TORCH_DEVICE=cpu
      - BTS_GNN_EPOCHS=100
      - BTS_GNN_HIDDEN_DIM=256
      - BTS_GNN_OUTPUT_DIM=256
      - BTS_GNN_LEARNING_RATE=0.001
      - BTS_VECTOR_DATABASE_DRIVER=qdrant
      - BTS_QDRANT_LOCATION=http://qdrant:6333
    volumes:
      - ./data:/app/data
      - ./config:/app/config

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  neo4j_data:
  neo4j_plugins:
  mongo_data:
  redis_data:
  qdrant_data:
