[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bioterms"
authors = [
  { name="Firefox2100", email="wangyunze16@gmail.com" },
]
description = "Biomedical Terminology Service"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "aiodataloader~=0.4.2",
    "aiosqlite~=0.21.0",
    "ariadne~=0.26.2",
    "fastapi~=0.121.3",
    "httpx~=0.28.1",
    "jinja2~=3.1.6",
    "neo4j~=6.0.3",
    "networkx~=3.5",
    "numpy~=2.3.5",
    "owlready2~=0.48",
    "pandas~=2.3.3",
    "prometheus-client~=0.23.1",
    "pyyaml~=6.0.2",
    "pydantic~=2.12.4",
    "pydantic-settings~=2.12.0",
    "pymongo~=4.15.4",
    "redis~=7.1.0",
    "rich~=14.2.0",
    "typer~=0.20.0",
    "uvicorn~=0.38.0",
]
dynamic = [
    "version"
]

[project.optional-dependencies]
test = [
    "deepdiff~=8.6.1",
    "pytest~=9.0.1",
    "pytest-asyncio~=1.3.0",
    "pytest-cov~=7.0.0",
    "pylint~=4.0.3",
]

[project.urls]
Homepage = "https://github.com/Firefox2100/biomedical-terminology-service"
Repository = "https://github.com/Firefox2100/biomedical-terminology-service.git"
Issues = "https://github.com/Firefox2100/biomedical-terminology-service/issues"

[project.scripts]
bioterms-cli = "bioterms.cli.cli:main"

[tool.setuptools.dynamic]
version = {attr = "bioterms.__version__"}
