name: Build Docker Image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
  release:
    types: [ published ]

jobs:
  push_to_registry:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract base metadata
        id: meta_base
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: firefox2100/biomedical-terminology-service

      - name: Extract CPU metadata
        id: meta_cpu
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: firefox2100/biomedical-terminology-service
          tags: |
            type=ref,event=branch,suffix=-cpu
            type=ref,event=tag,suffix=-cpu
            type=semver,pattern={{version}}-cpu
            type=raw,value=latest-cpu,enable={{is_default_branch}}

      - name: Extract GPU metadata
        id: meta_gpu
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: firefox2100/biomedical-terminology-service
          tags: |
            type=ref,event=branch,suffix=-gpu
            type=ref,event=tag,suffix=-gpu
            type=semver,pattern={{version}}-gpu
            type=raw,value=latest-gpu,enable={{is_default_branch}}

      - name: Build and push GPU image
        id: push_gpu
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          target: gpu
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta_base.outputs.tags }}
            ${{ steps.meta_gpu.outputs.tags }}
          labels: ${{ steps.meta_base.outputs.labels }}

      - name: Build and push CPU image
        id: push_cpu
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          target: cpu
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_cpu.outputs.tags }}
          labels: ${{ steps.meta_base.outputs.labels }}

      - name: Generate artifact attestation
        if: github.event_name != 'pull_request'
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/firefox2100/biomedical-terminology-service
          subject-digest: ${{ steps.push_gpu.outputs.digest }}
          push-to-registry: true
